// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgshhgrjwwaapblncfbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnc2hoZ3Jqd3dhYXBibG5jZmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTkzMzcsImV4cCI6MjA2Mzc3NTMzN30.BqdKTNfRYSpKYwJ_pqv8piVBnQ_hFFjpgE0N1y4Cqpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
